// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdSRrb9Y1asxrLZFgViBotFfyLFG-kIrY',
    appId: '1:1094342965592:web:50d32eaa054a73b6dc8d2d',
    messagingSenderId: '1094342965592',
    projectId: 'robotics-academy-app-2026',
    authDomain: 'robotics-academy-app-2026.firebaseapp.com',
    storageBucket: 'robotics-academy-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCh3_irkJmhDPKYvS7QbK5_K10VHKV58g',
    appId: '1:1094342965592:android:2e661ce6e5cbf712dc8d2d',
    messagingSenderId: '1094342965592',
    projectId: 'robotics-academy-app-2026',
    storageBucket: 'robotics-academy-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-CUxTQalvwubbJ1Ey3XK_hm5qed6kr_I',
    appId: '1:1094342965592:ios:13ac081f46edb287dc8d2d',
    messagingSenderId: '1094342965592',
    projectId: 'robotics-academy-app-2026',
    storageBucket: 'robotics-academy-app-2026.firebasestorage.app',
    iosBundleId: 'com.roboticsacademy.roboticsAcademyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-CUxTQalvwubbJ1Ey3XK_hm5qed6kr_I',
    appId: '1:1094342965592:ios:13ac081f46edb287dc8d2d',
    messagingSenderId: '1094342965592',
    projectId: 'robotics-academy-app-2026',
    storageBucket: 'robotics-academy-app-2026.firebasestorage.app',
    iosBundleId: 'com.roboticsacademy.roboticsAcademyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdSRrb9Y1asxrLZFgViBotFfyLFG-kIrY',
    appId: '1:1094342965592:web:a638b25157395b74dc8d2d',
    messagingSenderId: '1094342965592',
    projectId: 'robotics-academy-app-2026',
    authDomain: 'robotics-academy-app-2026.firebaseapp.com',
    storageBucket: 'robotics-academy-app-2026.firebasestorage.app',
  );
}
